enable docs (#12)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -72,3 +72,30 @@ jobs:
       - run: cabal check
       - run: cabal build all
       - run: cabal test --test-option=--color=always --test-show-details=always test-suite:silly-3.1-test
+  docs:
+    name: docs
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - uses: actions/checkout@v4
+      - uses: haskell-actions/setup@v2
+        id: setup-haskell
+        with:
+          ghc-version: 9.10.1
+      - run: cabal haddock veb --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs' --haddock-hyperlink-source --haddock-quickjump
+      - name: set reusable strings
+        id: strings
+        shell: bash
+        run: |-
+          docsdir=$(find dist-newstyle -type d -name "html")
+          if [[ -z "$docsdir" ]]; then
+            echo "Error: Documentation directory not found." >&2
+            exit 1
+          fi
+          echo "docs-output-dir=$docsdir" >> $GITHUB_OUTPUT
+      - name: publish docs
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ${{ steps.strings.outputs.docs-output-dir}}/veb
